const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const {allSizes,failures}=require('./workspace-qa.cjs');
const created=[];const requests=[];const frames=[];const messages=[];const errors=[];let browser;
const api='http://127.0.0.1:8000/api';const get=async url=>{const r=await fetch(api+url);assert.equal(r.status,200);return r.json();};
(async()=>{
 browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream',`--use-file-for-fake-audio-capture=${path.resolve(__dirname,'../../assets/scenarios/preset-dep-a/audio.wav')}`]});
 const page=await browser.newPage({viewport:{width:1440,height:900},permissions:['microphone']});page.setDefaultTimeout(45000);page.on('dialog',d=>d.accept());page.on('pageerror',e=>errors.push(e.message));
 page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/sessions')requests.push(r.postDataJSON());});
 page.on('response',async r=>{if(r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/sessions'&&r.status()===201)created.push({id:(await r.json()).session_id,mode:r.request().postDataJSON().mode});});
 page.on('websocket',ws=>{ws.on('framesent',e=>{if(Buffer.isBuffer(e.payload))frames.push(e.payload)});ws.on('framereceived',e=>{if(typeof e.payload==='string')messages.push(JSON.parse(e.payload));});});
 const nav=label=>page.getByRole('navigation',{name:'주 메뉴'}).getByRole('button',{name:label,exact:true});
 await page.goto('http://localhost:3000',{waitUntil:'networkidle'});await page.getByRole('button',{name:/상담 시작|시작하기|대시보드/}).first().click();
 assert.equal(await page.getByLabel('입력 방식',{exact:true}).inputValue(),'live');assert.equal(await page.locator('select[aria-label="입력 방식"] option[value="replay"]').count(),0);await allSizes(page,'manual-consultation-briefing');
 await page.getByRole('button',{name:'상담 시작 →',exact:true}).click();await page.getByRole('button',{name:'● 녹음 시작',exact:true}).waitFor();await page.waitForTimeout(5000);
 assert.equal(requests[0].mode,'live');assert.equal(requests[0].preset_id,undefined);assert.equal(requests[0].audio_ref,undefined);assert.equal(frames.length,0);assert.equal(messages.filter(m=>m.t==='utterance').length,0,'no automatic conversation before microphone start');
 await page.getByRole('button',{name:'● 녹음 시작',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.wb-chat-rows .wb-chat-entry').length>0);assert.ok(frames.length>0);assert.ok(messages.some(m=>m.t==='utterance'));
 await page.getByRole('button',{name:'■ 녹음 중지',exact:true}).click();await page.waitForTimeout(300);const stoppedCount=frames.length;await page.waitForTimeout(600);assert.equal(frames.length,stoppedCount,'microphone stop halts PCM');
 await page.getByRole('button',{name:'상담 종료',exact:true}).click();await page.getByRole('heading',{name:'종료 리포트',exact:true}).waitFor();
 await nav('이력').click();await allSizes(page,'history-records-separated');await page.getByRole('button',{name:'시연 음원',exact:true}).click();await page.locator('[data-preset-id]').first().waitFor();await allSizes(page,'history-presets-separated');assert.equal(requests.length,1,'browsing history never starts replay');
 await page.locator('[data-preset-id="preset-dep-a"]').locator('..').getByRole('button',{name:'음원 시연 시작',exact:true}).click();await page.getByRole('button',{name:'재생 종료',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.wb-heading button')?.disabled);
 assert.equal(requests[1].mode,'replay');assert.equal(await nav('이력').getAttribute('aria-current'),'page');assert.equal(await nav('상담').getAttribute('aria-current'),null);assert.equal(await page.getByRole('button',{name:'● 녹음 시작',exact:true}).count(),0);
 await nav('상담').click();await page.getByRole('heading',{name:'상담 준비',exact:true}).waitFor();assert.equal((await get(`/sessions/${created[1].id}`)).status,'ended');assert.equal(await page.getByLabel('입력 방식',{exact:true}).inputValue(),'live');assert.equal(requests.length,2);assert.equal(await page.locator('.wb-chat-entry').count(),0);
 await nav('이력').click();await page.getByLabel('이력 입력 방식').selectOption('replay');await page.locator('[data-session-id="FIXT-SESS-0A"]').locator('..').getByRole('button',{name:'TRACE 재생',exact:true}).click();await page.getByRole('button',{name:'소리 끄기',exact:true}).waitFor();
 assert.equal(requests[2].mode,'trace');assert.equal(await nav('이력').getAttribute('aria-current'),'page');await allSizes(page,'history-playback-separated');await nav('상담').click();await page.getByRole('heading',{name:'상담 준비',exact:true}).waitFor();assert.equal((await get(`/sessions/${created[2].id}`)).status,'ended');
 assert.equal(frames.length,stoppedCount,'REPLAY and TRACE never capture live microphone');assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);
 fs.writeFileSync(path.resolve(__dirname,'../qa-output/consultation-mode-qa.json'),JSON.stringify({created,checks:['manual LIVE default','zero audio/transcript before recording','real microphone fixture to STT','recording stop','history presets require click','separate playback screen and navigation','consultation exits REPLAY and TRACE into manual briefing','no microphone during playback','10 sizes for briefing/history/presets/playback'],errors,failures},null,2));console.log('PASS: manual consultation, actual STT, explicit history-only playback and safe return to consultation');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{
 await browser?.close();for(const {id,mode} of created){try{if((await get(`/sessions/${id}`)).status!=='running')continue;await new Promise(resolve=>{const ws=new WebSocket('ws://127.0.0.1:8000/ws');const timer=setTimeout(()=>{ws.close();resolve()},10000);ws.onopen=()=>ws.send(JSON.stringify({t:'hello',session_id:id,mode}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.t==='ready')ws.send(JSON.stringify({t:'end'}));if(m.t==='ping')ws.send(JSON.stringify({t:'pong'}));if(m.t==='ended'){clearTimeout(timer);ws.close();resolve()}};ws.onerror=()=>{clearTimeout(timer);resolve()};});}catch{}}
});
