"""pack storage tables

Revision ID: 10aa2956386d
Revises:
Create Date: 2026-08-29 22:27:03.513622

"""

from collections.abc import Sequence

# autogenerate 가 VECTOR 타입을 적으면서 import 는 넣어주지 않는다.
import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "10aa2956386d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # VECTOR 열은 pgvector 확장이 있어야 만들어진다. compose 초기화 스크립트를
    # 거치지 않은 DB(새 인스턴스·매니지드 서비스)에서 이 마이그레이션만 돌리면
    # 여기서 죽으므로 스키마와 같은 트랜잭션 안에서 보장한다.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pack",
        sa.Column("pack_version", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("product_code", sa.Text(), nullable=False),
        sa.Column("product_name", sa.Text(), nullable=False),
        sa.Column("product_category", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_by", sa.Text(), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column(
            "embedding_normalized", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "jargon_terms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint("product_category in ('deposit','loan')", name="ck_pack_category"),
        sa.CheckConstraint("embedding_dim > 0", name="ck_pack_embedding_dim"),
        sa.PrimaryKeyConstraint("pack_version"),
    )
    op.create_table(
        "item_embedding",
        sa.Column("pack_version", sa.Text(), nullable=False),
        sa.Column("embedding_id", sa.Text(), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pack_version"],
            ["pack.pack_version"],
            name="fk_item_embedding_pack",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("pack_version", "embedding_id"),
    )
    op.create_table(
        "pack_item",
        sa.Column("pack_version", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("axis", sa.Text(), nullable=True),
        sa.Column("requirement_elements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("legal_basis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("l1_patterns", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding_id", sa.Text(), nullable=True),
        sa.Column("plain_language", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("numeric_facts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("documents_required", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("forbidden_examples", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("risk_examples", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "axis is null or axis in ('omission','commission')", name="ck_pack_item_axis"
        ),
        sa.CheckConstraint(
            "type in ('required','forbidden','reference','risk')", name="ck_pack_item_type"
        ),
        sa.ForeignKeyConstraint(
            ["pack_version"], ["pack.pack_version"], name="fk_pack_item_pack", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("pack_version", "code"),
    )
    op.create_index("ix_pack_item_type", "pack_item", ["pack_version", "type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pack_item_type", table_name="pack_item")
    op.drop_table("pack_item")
    op.drop_table("item_embedding")
    op.drop_table("pack")
    # ### end Alembic commands ###
